---
- name: Create web user
  user: name=web
        state=present
        groups="sudo"
  sudo: yes

- name: install web packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - nginx
    - nodejs
    - npm

- name: remove default nginx configuration
  file: path=/etc/nginx/sites-available/default state=absent
  sudo: yes
  notify: restart nginx

- name: copy app
  template: src=index.html.j2 dest="{{base}}/app/index.html" group=www-data
  sudo: yes
  notify: restart nginx

- name: configure app
  template: src=app.j2 dest=/etc/nginx/sites-enabled/app group=www-data
  sudo: yes
  notify: restart nginx

- name: copy api
  synchronize:
    src=../api/
    dest="{{base}}/api/"
    rsync_opts=--exclude=.git,--exclude=node_modules,--exclude=etc
    recursive=yes
    delete=yes
  sudo: yes

- name: install api dependencies
  npm: path="{{base}}/api/"
  sudo: yes

- name: Install unit file
  template: src=api.service.j2 dest=/etc/systemd/system/api.service owner=root mode=644
  sudo: yes
  notify:
    - reload systemd

- name: enable api service
  service: name=api enabled=yes
  sudo: yes
  notify:
    - reload systemd

- name: run api service
  service: name=api state=started
  sudo: yes
  notify:
    - reload systemd
