---
- name: install web packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - nginx
    - nodejs

- name: remove default nginx configuration
  file: path=/etc/nginx/sites-available/default state=absent
  sudo: yes
  notify: restart nginx

# - name: configure main nginx proxy
#   copy: src=../main/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default group=www-data
#   sudo: yes
#   notify: restart nginx

- name: configure app
  copy: src=../app/etc/nginx/sites-available/app dest=/etc/nginx/sites-enabled/app group=www-data
  sudo: yes
  notify: restart nginx

- name: copy app
  copy: src=../app/www/ dest=/var/www/app/
  sudo: yes
  notify: restart nginx

# - name: Install unit file
#   copy: src=../api/etc/systemd/system/api.service dest=/etc/systemd/system/api.service owner=root mode=644
#   sudo: yes
#   notify:
#     - reload systemd
