---
# HAProxy supports "http" and "tcp". For SSL, SMTP, etc, use "tcp".
mode: http
daemonname: lb

# Balancing Algorithm. Available options:
# roundrobin, source, leastconn, source, uri
# (if persistance is required use, "source")
balance: roundrobin
