---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Download and install haproxy and socat
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - haproxy
    - socat

- name: Configure the haproxy cnf file with hosts
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy
  sudo: yes

- name: Start the haproxy service
  service: name=haproxy state=started enabled=yes
  sudo: yes
